# Generated by Django 5.0.6 on 2024-06-12 11:54

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(validators=[members.models.validate_age])),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('first_name', 'last_name', 'country', 'city')},
            },
        ),
    ]
